config/routes.rb
Rails.application.routes.draw do
  resources :colors
  resources :tallas
  resources :telas
  resources :documentos
  resources :ordenes

    root 'ordenes#index'

end

app/models/talla.rb
class Talla < ActiveRecord::Base
end

app/controllers/tallas_controller.rb
class TallasController < ApplicationController
  before_action :set_talla, only: [:show, :edit, :update, :destroy]

  # GET /tallas
  # GET /tallas.json
  def index
    @tallas = Talla.all
  end

  # GET /tallas/1
  # GET /tallas/1.json
  def show
  end

  # GET /tallas/new
  def new
    @talla = Talla.new
  end

  # GET /tallas/1/edit
  def edit
  end

  # POST /tallas
  # POST /tallas.json
  def create
    @talla = Talla.new(talla_params)

    respond_to do |format|
      if @talla.save
        format.html { redirect_to @talla, notice: 'Talla was successfully created.' }
        format.json { render :show, status: :created, location: @talla }
      else
        format.html { render :new }
        format.json { render json: @talla.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tallas/1
  # PATCH/PUT /tallas/1.json
  def update
    respond_to do |format|
      if @talla.update(talla_params)
        format.html { redirect_to @talla, notice: 'Talla was successfully updated.' }
        format.json { render :show, status: :ok, location: @talla }
      else
        format.html { render :edit }
        format.json { render json: @talla.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tallas/1
  # DELETE /tallas/1.json
  def destroy
    @talla.destroy
    respond_to do |format|
      format.html { redirect_to tallas_url, notice: 'Talla was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_talla
      @talla = Talla.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def talla_params
      params.require(:talla).permit(:nombre)
    end
end

app/helpers/tallas_helper.rb
module TallasHelper
end

app/views/tallas/_form.html.erb
<%= form_for(@talla) do |f| %>
  <% if @talla.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@talla.errors.count, "error") %> prohibited this talla from being saved:</h2>

      <ul>
      <% @talla.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tallas/edit.html.erb
<h1>Editing Talla</h1>

<%= render 'form' %>

<%= link_to 'Show', @talla %> |
<%= link_to 'Back', tallas_path %>

app/views/tallas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tallas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tallas.each do |talla| %>
      <tr>
        <td><%= talla.nombre %></td>
        <td><%= link_to 'Show', talla %></td>
        <td><%= link_to 'Edit', edit_talla_path(talla) %></td>
        <td><%= link_to 'Destroy', talla, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Talla', new_talla_path %>

app/views/tallas/new.html.erb
<h1>New Talla</h1>

<%= render 'form' %>

<%= link_to 'Back', tallas_path %>

app/views/tallas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @talla.nombre %>
</p>

<%= link_to 'Edit', edit_talla_path(@talla) %> |
<%= link_to 'Back', tallas_path %>