config/routes.rb
Rails.application.routes.draw do
  resources :colors
  resources :tallas
  resources :telas
  resources :documentos
  resources :ordenes

    root 'ordenes#index'

end

app/models/color.rb
class Color < ActiveRecord::Base
    has_many :agregar_tallas
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  before_action :set_color, only: [:show, :edit, :update, :destroy]

  # GET /colors
  # GET /colors.json
  def index
    @colors = Color.all
  end

  # GET /colors/1
  # GET /colors/1.json
  def show
  end

  # GET /colors/new
  def new
    @color = Color.new
  end

  # GET /colors/1/edit
  def edit
  end

  # POST /colors
  # POST /colors.json
  def create
    @color = Color.new(color_params)

    respond_to do |format|
      if @color.save
        format.html { redirect_to @color, notice: 'Color was successfully created.' }
        format.json { render :show, status: :created, location: @color }
      else
        format.html { render :new }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colors/1
  # PATCH/PUT /colors/1.json
  def update
    respond_to do |format|
      if @color.update(color_params)
        format.html { redirect_to @color, notice: 'Color was successfully updated.' }
        format.json { render :show, status: :ok, location: @color }
      else
        format.html { render :edit }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colors/1
  # DELETE /colors/1.json
  def destroy
    @color.destroy
    respond_to do |format|
      format.html { redirect_to colors_url, notice: 'Color was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color
      @color = Color.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def color_params
      params.require(:color).permit(:nombre)
    end
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/views/colors/_form.html.erb
<%= form_for(@color) do |f| %>
  <% if @color.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@color.errors.count, "error") %> prohibited this color from being saved:</h2>

      <ul>
      <% @color.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colors/edit.html.erb
<h1>Editing Color</h1>

<%= render 'form' %>

<%= link_to 'Show', @color %> |
<%= link_to 'Back', colors_path %>

app/views/colors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Colors</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colors.each do |color| %>
      <tr>
        <td><%= color.nombre %></td>
        <td><%= link_to 'Show', color %></td>
        <td><%= link_to 'Edit', edit_color_path(color) %></td>
        <td><%= link_to 'Destroy', color, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Color', new_color_path %>

app/views/colors/new.html.erb
<h1>New Color</h1>

<%= render 'form' %>

<%= link_to 'Back', colors_path %>

app/views/colors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @color.nombre %>
</p>

<%= link_to 'Edit', edit_color_path(@color) %> |
<%= link_to 'Back', colors_path %>