config/routes.rb
Rails.application.routes.draw do
  resources :colors
  resources :tallas
  resources :telas
  resources :documentos
  resources :ordenes

    root 'ordenes#index'

end

app/models/tela.rb
class Tela < ActiveRecord::Base
    has_many :ordenes
end

app/controllers/telas_controller.rb
class TelasController < ApplicationController
  before_action :set_tela, only: [:show, :edit, :update, :destroy]

  # GET /telas
  # GET /telas.json
  def index
    @telas = Tela.all
  end

  # GET /telas/1
  # GET /telas/1.json
  def show
  end

  # GET /telas/new
  def new
    @tela = Tela.new
  end

  # GET /telas/1/edit
  def edit
  end

  # POST /telas
  # POST /telas.json
  def create
    @tela = Tela.new(tela_params)

    respond_to do |format|
      if @tela.save
        format.html { redirect_to @tela, notice: 'Tela was successfully created.' }
        format.json { render :show, status: :created, location: @tela }
      else
        format.html { render :new }
        format.json { render json: @tela.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /telas/1
  # PATCH/PUT /telas/1.json
  def update
    respond_to do |format|
      if @tela.update(tela_params)
        format.html { redirect_to @tela, notice: 'Tela was successfully updated.' }
        format.json { render :show, status: :ok, location: @tela }
      else
        format.html { render :edit }
        format.json { render json: @tela.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /telas/1
  # DELETE /telas/1.json
  def destroy
    @tela.destroy
    respond_to do |format|
      format.html { redirect_to telas_url, notice: 'Tela was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tela
      @tela = Tela.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tela_params
      params.require(:tela).permit(:Referencia, :nombre, :descripcion)
    end
end

app/helpers/telas_helper.rb
module TelasHelper
end

app/views/telas/_form.html.erb
<%= form_for(@tela) do |f| %>
  <% if @tela.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tela.errors.count, "error") %> prohibited this tela from being saved:</h2>

      <ul>
      <% @tela.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Referencia %><br>
    <%= f.text_field :Referencia %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/telas/edit.html.erb
<h1>Editing Tela</h1>

<%= render 'form' %>

<%= link_to 'Show', @tela %> |
<%= link_to 'Back', telas_path %>

app/views/telas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Telas</h1>

<table>
  <thead>
    <tr>
      <th>Referencia</th>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @telas.each do |tela| %>
      <tr>
        <td><%= tela.Referencia %></td>
        <td><%= tela.nombre %></td>
        <td><%= tela.descripcion %></td>
        <td><%= link_to 'Show', tela %></td>
        <td><%= link_to 'Edit', edit_tela_path(tela) %></td>
        <td><%= link_to 'Destroy', tela, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tela', new_tela_path %>

app/views/telas/new.html.erb
<h1>New Tela</h1>

<%= render 'form' %>

<%= link_to 'Back', telas_path %>

app/views/telas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Referencia:</strong>
  <%= @tela.Referencia %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @tela.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @tela.descripcion %>
</p>

<%= link_to 'Edit', edit_tela_path(@tela) %> |
<%= link_to 'Back', telas_path %>